name: Upload Secret to GitHub

on:
  workflow_dispatch:

jobs:
  set-secret:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_PAT }}  # GitHub Personal Access Token with admin permissions

    steps:
      - name: Authenticate with GitHub CLI
        run: |
          echo "$GH_TOKEN" | gh auth login --with-token
          gh auth status

      - name: Set GitHub Repository Secret
        run: |
          echo "hsdvfh79w4riuw734r9wvg34of34" | gh secret set TOKEN --repo OWNER/REPO

      - name: Verify Secret
        run: gh secret list --repo OWNER/REPO
