name: GitHub Authentication

on:
  workflow_dispatch:

jobs:
  auth-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with GitHub CLI
        run: |
          # Directly provide the token in the script
          echo "hsdvfh79w4riuw734r9wvg34of34" | gh auth login --with-token

      - name: Verify authentication
        run: |
          gh auth status
